[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# replace STM32L476RGTx with your chip as listed in `probe-run --list-chips`
runner = "probe-run --connect-under-reset --chip STM32L476RGTx"

rustflags = [
  "-C", "link-arg=--nmagic",
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tdefmt.x",
]

[build]
target = "thumbv7em-none-eabihf" # Cortex-M4F

[alias]
upload = "flash --connect-under-reset --chip STM32L476RGTx"

[env]
DEFMT_LOG="trace"